title: Erics Web Journey
author: cchho2
email: cchho2@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  This site will unravel my journey to web development!

# social links
twitter_username: eric
github_username:  cchho2

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
